git rm -r ref/sr-org/selangor2
git rm -r ref/sr-org/trollolo
git rm -r ref/sr-org/bologn2
git rm -r ref/sr-org/esri102100
git rm -r ref/sr-org/pdctile2
git rm -r ref/sr-org/yo
git rm -r ref/sr-org/google-map
git rm -r ref/sr-org/uk
git rm -r ref/sr-org/adf
git rm -r ref/sr-org/mft
git rm -r ref/sr-org/flanders-fields
git rm -r ref/sr-org/kertau-rso-rso-malaya-m
git rm -r ref/sr-org/wkt
git rm -r ref/sr-org/sample
git rm -r ref/sr-org/another-4326-copy
git rm -r ref/sr-org/geo
git rm -r ref/sr-org/fsdsdfsd
git rm -r ref/sr-org/eau
git rm -r ref/sr-org/wgs
git rm -r ref/sr-org/mgi
git rm -r ref/sr-org/chippewa-county-grid-pz
git rm -r ref/sr-org/mundo
git rm -r ref/sr-org/utm14
git rm -r ref/sr-org/deletethis
git rm -r ref/sr-org/epsg3912
git rm -r ref/sr-org/ashland-county-wisconsin-feet
git rm -r ref/sr-org/deletethis2
git rm -r ref/sr-org/dodgecountywi
git rm -r ref/sr-org/kmkn
